oiko_leaflet.settings:
  type: config_object
  label: 'Oiko Leaflet Settings'
  mapping:
    url_template:
      type: text
      label: 'URL Template'
    attribution:
      type: text
      label: 'Attribution'