version: "2"
services:

  database:
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: oiko
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306

  drush:
    image: computerminds/drush:8
    volumes:
      - ./repo-root:/app
      - ./scripts:/scripts
    depends_on:
      - database
    links:
      - database
    # The entrypoint of the image is defined as drush, so we override that here.
    entrypoint: bash -xe /scripts/site-install.sh
