entity_share_notifier.entity_share_subscriber.*:
  type: config_entity
  label: 'Entity share subscriber config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    subscriber_url:
      type: string
      label: 'URL'
    basic_auth_username:
      type: string
      label: 'Basic auth username'
    basic_auth_password:
      type: string
      label: 'Basic auth password'
    remote_id:
      type: string
      label: 'Remote ID'
    remote_config_id:
      type: string
      label: 'Remote Config import ID'
    channel_ids:
      type: sequence
      label: 'Channel IDs'
      nullable: true
      sequence:
        type: string
        label: 'Channel ID'
