entity_share_notifier.entity_share_subscriber.*:
  type: config_entity
  label: 'Entity share subscriber config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    subscriber_url:
      type: string
      label: 'URL'
    auth:
      type: mapping
      mapping:
        pid:
          label: 'Plugin ID'
          type: string
        uuid:
          label: 'UUID'
          type: string
        data:
          type: mapping
          label: 'Credential data'
          mapping:
            credential_provider:
              type: string
              label: 'Credential provider'
            storage_key:
              type: string
              label: 'Storage key'
    remote_id:
      type: string
      label: 'Remote ID'
    remote_config_id:
      type: string
      label: 'Remote Config import ID'
    channel_ids:
      type: sequence
      label: 'Channel IDs'
      nullable: true
      sequence:
        type: string
        label: 'Channel ID'
