# Schema for the configuration files of the CIDOC module.

cidoc.cidoc_entity_bundle.*:
  type: config_entity
  label: 'CIDOC entity class config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    crm_entity:
      type: string
      label: 'CRM Entity'
    group:
      type: text
      label: 'Group'
    weight:
      type: integer
      label: 'Weight'
    description:
      type: text
      label: 'Description'
    examples:
      type: text
      label: 'Description'
    geoserializers:
      type: sequence
      label: 'Enabled geoserializer plugins for this bundle'
      sequence:
        type: string
        label: 'Geoserializer plugin ID'
    uuid:
      type: string

cidoc.cidoc_property.*:
  type: config_entity
  label: 'CIDOC property config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    reverse_label:
      type: label
      label: 'Reverse label'
    domain_bundles:
      type: sequence
      label: 'Allowed bundles of related entities'
      sequence:
        type: string
        label: 'Domain bundle'
    range_bundles:
      type: sequence
      label: 'Target bundles of related entities'
      sequence:
        type: string
        label: 'Range bundle'
    uuid:
      type: string
    editability:
      type: mapping
      label: 'Which endpoint entities the property will be editable on.'
      mapping:
        domain:
          type: boolean
          label: 'Editable on domain entities'
        range:
          type: boolean
          label: 'Editable on range entities'
    timesubwidget:
      type: mapping
      label: 'Which endpoint widget will use the time subwidget.'
      mapping:
        domain:
          type: mapping
          label: 'Domain subwidget settings'
          mapping:
            type:
              type: string
            title_template:
              type: string
            sub_property:
              type: string

        range:
          type: mapping
          label: 'Range subwidget settings'
          mapping:
            type:
              type: string
            title_template:
              type: string
            sub_property:
              type: string
    bidirectional:
      type: boolean
      label: 'Whether this property is symmetric.'

views.filter.cidoc_bundle:
  type: views.filter.in_operator
  label: 'CIDOC Bundle'
