domain: ''
domains_option: 1
domains_list: ''
eu_only: false
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
export:
  folder: custom
langcode: en
popup_agreed:
  value: '<h2>Thank you for accepting cookies</h2><p>You can now hide this message or find out more about cookies.</p>'
  format: restricted_html
popup_agree_button_message: 'I agree'
popup_agreed_enabled: false
popup_bg_hex: '212121'
popup_clicking_confirmation: true
popup_delay: 1
popup_disagree_button_message: 'Read privacy policy'
popup_enabled: true
popup_find_more_button_message: 'Read privacy policy'
popup_height: null
popup_hide_agreed: false
popup_hide_button_message: Hide
popup_info:
  value: '<h2>We use cookies on this website to enhance your user experience. Read more in our <a href="https://oiko.world/privacy-policy#cookies">privacy policy</a>.</h2>'
  format: restricted_html
popup_link: 'https://oiko.world/privacy-policy#cookies'
popup_link_new_window: true
popup_position: true
popup_text_hex: ffffff
popup_width: 100%
method: default
disagree_button_label: 'No, thanks'
disabled_javascripts: ''
whitelisted_cookies: ''
consent_storage_method: do_not_store
withdraw_message:
  value: '<h2>We use cookies on this site to enhance your user experience</h2><p>You have given your consent for us to set cookies.</p>'
  format: plain_text
withdraw_action_button_label: 'Withdraw consent'
withdraw_tab_button_label: 'Privacy settings'
withdraw_enabled: false
popup_info_template: legacy
cookie_categories: ''
enable_save_preferences_button: true
save_preferences_button_label: 'Save preferences'
accept_all_categories_button_label: 'Accept all cookies'
fix_first_cookie_category: true
select_all_categories_by_default: false
withdraw_button_on_info_popup: false
domain_all_sites: false
uuid: 323a3968-8bf6-4e2a-895a-af9fb5e5cb76
