_core:
  default_config_hash: 8KH8twieoab8UCR9Tpd8WhkfhJp-G_gXX4yUq7ZO3Ck
display_denied_message: false
access_denied_message: 'Access denied. You must log in to view this page.'
access_denied_message_type: error
redirect_authenticated_users_to: ''
user_login_path: /user/login
default_redirect_code: 302
destination_parameter_override: ''
match_noredirect_pages: ''
redirect_to_destination: false
