basicshib.settings:
  type: config_object
  mapping:
    login_link_label:
      type: string
      label: 'Login link label'

    default_post_login_redirect_path:
      type: string
      label: 'Post-login redirect path'

    messages:
      type: mapping
      label: 'Messages'
      mapping:
        generic_login_error:
          type: string
          label: 'Generic login error message'

        external_redirect_error:
          type: string
          label: 'External redirect error message'

        account_blocked_error:
          type: string
          label: 'Account blocked message'

        login_disallowed_error:
          type: string
          label: 'Login disallowed message'

        user_creation_not_allowed_error:
          type: string
          label: 'User creation not allowed message'

    plugins:
      type: mapping
      label: 'Plugins'
      mapping:
        user_provider:
          type: string
          label: 'User provider plugin'

        auth_filter:
          type: sequence
          label: 'Authentication filters'
          sequence:
            type: string
            label: 'Authentication filter'

    handlers:
      type: mapping
      label: 'Handlers'
      mapping:
        login:
          type: string
          label: 'Login handler'
        logout:
          type: string
          label: 'Logout handler'

    attribute_map:
      type: mapping
      label: 'Attributes'
      mapping:
        key:
          type: mapping
          label: 'Key attributes'
          mapping:
            name:
              type: string
              label: 'Name attribute'

            mail:
              type: string
              label: 'Mail attribute'

            session_id:
              type: string
              label: 'Session ID attribute'

        optional:
          type: sequence
          label: 'Optional attributes'
          sequence:
            type: string
            label: 'Optional attribute'
            mapping:
              id:
                type: string
                label: 'Attribute id'
              name:
                type: string
                label: 'Attribute name'

basicshib.auth_filter:
  type: config_object
  mapping:
    create:
      type: mapping
      label: 'User creation settings'
      mapping:
        allow:
          type: boolean
          label: 'Allow user creation'
        error:
          type: string
          label: 'Error message to show when creation is denied'

